---
functional:
  - Сайт должен быть доступен на различных устройствах
  - сайт должен иметь многоязычную поддержку интерфейса
  - Сайт должен иметь мобильную версию
  - В программе должна быть возможность создать игру с любым пользователем из зарегистрированных, другом ( по ссылке- приглашению) или ботом
  - Доступ к созданию игры должен быть только у авторизованных пользователей
  - При создании игры можно выбрать уровень сложности, задачу или выбрать рандомную игру
  - В программе можно авторизоваться через Github, Discord
  - В программе можно общаться с другими участниками в чате
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  
implicit:
  - Авторизация пользователя, создание личного кабинета
  - Наличие в личном кабинете статистики игр, побед и поражений
  - Изменение настроек профайла (изменение имени, эл.почты, аватара и т.д.)

