---
functional:
  - Сайт должен быть доступен на различных устройствах
  - сайт должен иметь многоязычную поддержку интерфейса
  - Сайт должен иметь мобильную версию
  - В программе должна быть возможность создать игру с любым пользователем из зарегистрированных, другом ( по ссылке- приглашению) или ботом
  - Доступ к созданию игры должен быть только у авторизованных пользователей
  - При создании игры можно выбрать уровень сложности, задачу или выбрать рандомную игру, установить таймер игры
  - В программе можно авторизоваться через Github
  - В программе можно авторизоваться через Discord
  - В программе можно авторизоваться с помощью логина и пароля
  - В программе можно зарегистрироваться с помощью электронной почты
  - При авторизации можно восстановить пароль
  - В программе можно общаться с другими участниками
  - Есть звуковое сопровождение
  - В профайле пользователя есть данные о его рейтинге
  - В профайле пользователя есть дата регистрации на сайте
  - В профайле пользователя есть статистика игр- победы, поражения, ничьи, их даты, время; информация об оппонентах
  - При наведении курсора на никнейм пользователя выпадает окно с его рейтингом, кол-вом сыгранных игр, побед, поражений и ничьих
  - У ботов есть значок робота рядом с никнеймом
  - Во время игры можно выбрать язык программирования
  - Во время игры можно выбрать светлую/темную темы для поля кода
  - Победителем становится тот, кто раньше напишет код и нажмет run
  - После создания игры включается обратный отсчет таймера
  - 
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  
implicit:
  - Авторизация пользователя, создание личного кабинета
  - Наличие в личном кабинете статистики игр, побед и поражений
  - Изменение настроек профайла (изменение имени, эл.почты, аватара и т.д.)
