---
functional:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - сайт должен предоставлять пользователям возможность играть друг с другом, с виртуальным соперником, командами
  - сайт должен иметь многоязычную поддержку интерфейса
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Авторизация пользователя, создание личного кабинета
  - Наличие в личном кабинете статистики игр, побед и поражений
