---
functional:
  - Сайт должен быть доступен на различных устройствах
  - сайт должен иметь многоязычную поддержку интерфейса
  - Сайт должен иметь мобильную версию
  - В программе должна быть возможность создать игру с любым пользователем из зарегистрированных, другом ( по ссылке- приглашению) или ботом
  - Доступ к созданию игры должен быть только у авторизованных пользователей
  - При создании игры можно выбрать уровень сложности, задачу или выбрать рандомную игру, установить таймер игры
  - В программе можно авторизоваться через Github
  - В программе можно авторизоваться через Discord
  - В программе можно авторизоваться с помощью логина и пароля
  - В программе можно зарегистрироваться с помощью электронной почты
  - При авторизации можно восстановить пароль
  - В программе можно общаться с другими участниками
  - Есть звуковое сопровождение
  - В профайле пользователя есть данные о его рейтинге
  - В профайле пользователя есть дата регистрации на сайте
  - В профайле пользователя есть статистика игр- победы, поражения, игрок сдался, их даты, время; информация об оппонентах
  - При наведении курсора на никнейм пользователя выпадает окно с его рейтингом, кол-вом сыгранных игр, побед, поражений и сдач
  - У ботов есть значок робота рядом с никнеймом
  - Во время игры можно выбрать язык программирования
  - Во время игры можно выбрать светлую/темную темы для поля кода  
  - После создания игры включается обратный отсчет таймера
  - При клике на свой никнейм выпадает окно со списком, в котором есть- настройки, рейтинг пользователей, турниры, задачи, кланы
  - В задачах (Task) есть список создателей задач с уровнем сложности, тэгами, датой и временем создания
  - Каждый авторизованный пользователь может создать собственую задачу
  - Можно просмотреть список турниров
  - Можно просмотреть список кланов, никнеймы их создателей
  - Можно просмотреть рейтинг пользователей за неделю, месяц или за все время
  - Можно просмотреть рейтинг пользователей по 20,30,40 или 50 строк
  - Можно искать пользователя в рейтинге пользователей по имени
  - В рейтинге пользователей можно просмотреть дату регистрации пользователя, как он авторизован (через Github или нет)
  - На главной странице можно просмотреть историю игр пользователей - вкладка History
  - На главной странице можно просмотреть турниры - вкладка tournaments
  - На главной странице можно посмотреть таблице лидеров отдельной таблицей, за неделю, месяц или все время
  - Если игра заканчивается ничьей, в рейтинг участников она не входит
  - При клике на никнейм выпадает окно, где есть кнопки для перехода в Source code, Hexlet, Join Discord, Tg codebattle и выход из ЛК (Sing out)
  - В рейтинг пользователя засчитываются игры, которые заканчиваются победой, поражением или игрок сдался
  - Есть кнопка перехода на аккаунт Github 
  - Каждый язык программирования в списке при выборе в игре имеет свой значок
  - Оппоненты видят код друг друга
  - На экране игры есть кнопки для просмотра истории и выхода на главную страницу
  - При выходе на главную страницу во время игры есть кнопка возврата к игре
  - Примеры, данные в задаче игры, нельзя скопировать во время игры
  - Победителем становится тот, кто раньше правильно напишет код и нажмет run
  - Если код в игре написан неправильно, это отобразится во вкладке output
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  
implicit:
  - Авторизация пользователя, создание личного кабинета
  - Наличие в личном кабинете статистики игр, побед и поражений
  - Изменение настроек профайла (изменение имени, эл.почты, аватара и т.д.)
  - Есть кнопка перехода на аккаунт Github  с рисунком котика в ЛК
